import turtle as t
t.screensize(600, 600)
t.penup()
t.goto(-150, 160)
t.pendown()
t.write('20255120201100-廖懋雄 ',font=('黑体',20,'normal'))
t.penup()
t.goto(100, 150)
t.pendown()
t.pensize(2)
t.pencolor("purple")
t.fillcolor("purple")
t.penup()
t.goto(0, -120)
t.pendown()
t.begin_fill()
t.circle(120)
t.end_fill()
t.pencolor("blue")
t.fillcolor("blue")
t.penup()
t.goto(0, -90)
t.pendown()
t.begin_fill()
t.circle(90)
t.end_fill()
t.pencolor("yellow")
t.fillcolor("yellow")
t.penup()
t.goto(0, -60)
t.pendown()
t.begin_fill()
t.circle(60)
t.end_fill()
t.pencolor("red")
t.fillcolor("red")
t.penup()
t.goto(0, -30)
t.pendown()
t.begin_fill()
t.circle(30)
t.end_fill()
t.done()