import turtle as t
t.screensize(600, 600)
t.penup()
t.goto(-150, 300)
t.pendown()
t.write('20255120201140-李泓毅 ',font=('黑体',20,'normal'))
t.penup()
t.goto(100, 150)
t.pendown()
t.pensize(5)
t.pencolor("purple")
t.fillcolor("purple")
t.penup()
t.goto(0, -200)
t.pendown()
t.begin_fill()
t.circle(200)
t.end_fill()
t.pencolor("blue")
t.fillcolor("blue")
t.penup()
t.goto(0, -150)
t.pendown()
t.begin_fill()
t.circle(150)
t.end_fill()
t.pencolor("yellow")
t.fillcolor("yellow")
t.penup()
t.goto(0, -100)
t.pendown()
t.begin_fill()
t.circle(100)
t.end_fill()
t.pencolor("red")
t.fillcolor("red")
t.penup()
t.goto(0, -50)
t.pendown()
t.begin_fill()
t.circle(50)
t.end_fill()
t.done()